#!/usr/bin/env bash
# Idempotent repository setup for the GizzNote Cloud Agent environment.
# Installs PostgreSQL + Bun, project dependencies, a local .env.local, and
# initializes the local development database. Safe to run repeatedly.
set -euo pipefail
cd "$(dirname "$0")/.."

# 1. System dependency: PostgreSQL (used for vault + chat persistence).
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
fi

# 2. Bun (package manager + runtime).
if [ ! -x "$HOME/.bun/bin/bun" ] && ! command -v bun >/dev/null 2>&1; then
  curl -fsSL https://bun.sh/install | bash
fi
export PATH="$HOME/.bun/bin:$PATH"

# 3. Project dependencies.
bun install

# 4. Local env file (gitignored). DATABASE_URL points at the local Postgres.
#    Secrets (OPENROUTER_API_KEY, Clerk keys) are injected as env vars by Cloud
#    Agent and read from process.env, so they are not written here.
if [ ! -f .env.local ]; then
  cat > .env.local <<'EOF'
# Generated by .cursor/install.sh for local development.
DATABASE_URL=postgresql://gizznote:gizznote@127.0.0.1:5432/gizznote
EOF
fi

# 5. Start Postgres and initialize the dev role/database (idempotent) so the
#    schema is baked into the environment build snapshot.
sudo pg_ctlcluster 16 main start || true
until sudo -u postgres pg_isready -q; do sleep 1; done
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='gizznote'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE ROLE gizznote LOGIN PASSWORD 'gizznote';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='gizznote'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE gizznote OWNER gizznote;"

echo "GizzNote install complete."
